### PR TITLE
Fix #54: Validate rules before adding them to the database.

### LINKED ISSUE #54: Rules endpoint should handle errors
The rules endpoint is returning ok no matter what happened with the provided rule.

Then if a rule is incorrect, it will crash later on when trying to use it.

### PR DESCRIPTION
**Pull request by benfle**

### CODE REVIEW

**Comment by jduthon** [comment]
Validation part seems good.
Though I tend to think on the HTTP endpoint side we should try/catch and report the error as the response when an error is caught.

**Comment by benfle** [comment]
Isn't that how it works already?

```
{"error":"Unknown condition type: undefined"}
{"error":"Invalid condition: data should have required property 'ip'"}
```

**Comment by jduthon** [comment]
My bad, I did not know but Express seems to be handling that already and the server is answering with a 500 with the correct error.
Then it's perfect! 👍

**Comment by znarf** [comment]
@jduthon 500 doesn't sounds good, should that be a 400 instead?

**Comment by jduthon** [comment]
@znarf Yeah you are right, 400 would make more sense.

**Comment by znarf** [comment]
also, before it's too late, let's rename 'ip' to 'address'.

**Pull request merged**
