### PR TITLE
Issue 77: Input incoming count

### PR DESCRIPTION
**Pull request by benfle**
screen shot 2017-12-13 at 10 25 24 am

### CODE REVIEW

**Comment by benfle** [comment]
The rule PR needs to be merged first since this one is based on it.

@jduthon we need to update the dashboard status page to use the new model

**Comment by jduthon** [comment]
@benfle 
Could we make the speeds of accepted/reject consistent between `rules` and `inputs`.
Right now a `rule` encapsulates the `blocked` and `accepted` properties in a `speed` property.
Whereas here I see that they are directly attached as `blocked` and `accepted`.
I tend to prefer this version, with no `speed` but directly `blocked` and `accepted` property.
In fine I am fine with both, but it would be nice if they can be consistent.
What do you think?

**Comment by znarf** [comment]
Let's fix the conflict.

**Comment by jduthon** [comment]
UI build is updated.
The Accepted/Reject | Blocked/Passed are in common.
I know the design is not yet perfect, but it's in common so we can just update it in the one place when we figure out a bit better what we want.

**Pull request merged**
