### PR TITLE
Fix #34: Blocking rules backend

### LINKED ISSUE #34: Blocking rules backend
The backend should support the following features:

* Create a blocking rule (from an IP address for now, more complex ones later)
* Remove a blocking rule
* List the blocking rules in the database
* Persist the database of rules
* Count number of requests that match a rule

### PR DESCRIPTION
**Pull request by benfle**

### CODE REVIEW

**Comment by jduthon** [comment]
Seems good to me.
Only thing I can think of is we might want some custom matchers to be easily added, but I believe this is for later.

**Comment by benfle** [comment]
@jduthon Yes, those are for later as needs arise.

**Comment by znarf** [comment]
Should we introduce a 'data' directory where we can store what we want without polluting the root directory?

**Comment by znarf** [comment]
For the record, I don't like the 'ip' name for the rule.

I'm also noticing there is an hardcoded ['address', 'value']. This is hinting that this property is becoming core and should be documented so.

**Pull request merged**
