### PR TITLE
Update /metrics endpoint

### PR DESCRIPTION
**Pull request by znarf**

### CODE REVIEW

**Comment by znarf** [comment]
Before merging, let's make sure that the UI works:
- either by fixing the old /metrics and /activity endpoints
- either by updating the UI to only request from the new endpoints, then have the old endpoints deleted

**Comment by benfle** [comment]
I would strongly encourage you to fix the UI to get rid of these temporary HTTP endpoints which (obviously) cause bugs. But if you have too much on your plate I can take an hour to update these endpoints.

**Comment by znarf** [comment]
@benfle @jduthon is currently working on an UI update, which would just do that.

**Comment by znarf** [comment]
Closing the PR because Github doesn't see latest commits.

**Pull request merged**
