### PR TITLE
[WIP] Move input validation in the pipeline

### PR DESCRIPTION
**Pull request by znarf**
Implementation details:
 - log entering the pipeline should be JS object, otherwise, we have to decode the Map to validate it, I see that as inefficient

Open Issue:
- I'm wondering where input/log-schema.json should be in the project. the current place looks not correct

To do:
- convert the Nginx input from Map to object, and remove the Map to object conversion in the pipeline

### CODE REVIEW

**Comment by benfle** [comment]
I'm not in favor of changing the log maps into JS objects.

If you do that you will have to handle both "formats" in the pipeline. For example, if you report a validation error on a log it will be a JS object, but if it is an error in a processor, it will be as a Map.

Another problem is that we will hide the transformation from JS object to map inside the pipeline. People will send JS objects to the pipeline and their code will be called later with log maps.

If the JSON schema validation library does not work for us then let's find another way to do the validation.

**Comment by znarf** [comment]
People are not sending Immutable Map over the network, and they will never do.

When receiving structured logs over the network, we receive JSON: on Syslog, on Http, on WebSocket.

That's the reality, this format is existing, and we better embrace that.

**Comment by benfle** [comment]
The whole point of the input and format modules is to isolate the pipeline from the various protocols and formats used to transfer logs over the network. Not all formats are JSON (NGINX for example). So if we want to have a shared validation logic we should do it in the pipeline with the immutable data model we currently use.

The whole pipeline manipulates data as immutable maps. It doesn't make sense to manipulate logs as JavaScript objects in one place in the pipeline and as immutable maps in another place.

We embrace the JSON format but as a format, not as the generic data model to represent all inputs of our pipeline. We can use the JSON schema to validate the input of the JSON format parser to ensure that we translate into a valid immutable map. But I think it would be a mistake to let this JSON format/validation leak into the pipeline module.

**Comment by znarf** [comment]
I addressed the comments from this conversation and will open a fresh PR that is more pragmatic.

**Pull request closed without merging**
