### PR TITLE
Update input documentation

### PR DESCRIPTION
**Pull request by znarf**

### CODE REVIEW

**Comment by realies** [comment]
#111 was requested a bit too late, can update it when this is merged

**Comment by znarf** [comment]
@realies which section do you think is unnecessary? can you point on the lines?

**Comment by realies** [comment]
Was referring to https://github.com/access-watch/access-watch/pull/111/files#diff-861c79f8024bbde6ed781eaea1f172c6 and the mentioning of how `access_log` can be used within `server_name` statements. It might be irrelevant to have it though.

**Comment by znarf** [comment]
@realies yes, I don't see the added value compared with the previous line.

**Pull request merged**
